/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Card {
  'rank' : { 'ace' : null } |
    { 'six' : null } |
    { 'ten' : null } |
    { 'two' : null } |
    { 'three' : null } |
    { 'five' : null } |
    { 'four' : null } |
    { 'jack' : null } |
    { 'king' : null } |
    { 'nine' : null } |
    { 'queen' : null } |
    { 'eight' : null } |
    { 'seven' : null },
  'suit' : { 'diamonds' : null } |
    { 'clubs' : null } |
    { 'spades' : null } |
    { 'hearts' : null },
}
export type GamePhase = { 'playing' : null } |
  { 'finished' : null } |
  { 'waiting' : null };
export interface GameRoom {
  'status' : RoomStatus,
  'deck' : Array<Card>,
  'scores' : Array<bigint>,
  'currentTurn' : bigint,
  'players' : Array<Player>,
  'gameType' : GameType,
  'phase' : GamePhase,
  'roomId' : bigint,
  'maxPlayers' : bigint,
}
export type GameType = { 'santase' : null } |
  { 'belot' : null } |
  { 'spades' : null } |
  { 'durak' : null };
export interface Player {
  'id' : Principal,
  'username' : string,
  'hand' : Array<Card>,
  'wins' : bigint,
  'losses' : bigint,
  'totalGames' : bigint,
}
export type RoomStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface UserProfile {
  'username' : string,
  'wins' : bigint,
  'losses' : bigint,
  'totalGames' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGameRoom' : ActorMethod<[GameType, bigint], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRoomDetails' : ActorMethod<[bigint], GameRoom>,
  'getRoomListByPlayers' : ActorMethod<[], Array<[bigint, GameRoom]>>,
  'getRoomListByStatus' : ActorMethod<[RoomStatus], Array<[bigint, GameRoom]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGameRoom' : ActorMethod<[bigint, string], undefined>,
  'leaveGameRoom' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];