/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameType = IDL.Variant({
  'santase' : IDL.Null,
  'belot' : IDL.Null,
  'spades' : IDL.Null,
  'durak' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalGames' : IDL.Nat,
});
export const RoomStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Card = IDL.Record({
  'rank' : IDL.Variant({
    'ace' : IDL.Null,
    'six' : IDL.Null,
    'ten' : IDL.Null,
    'two' : IDL.Null,
    'three' : IDL.Null,
    'five' : IDL.Null,
    'four' : IDL.Null,
    'jack' : IDL.Null,
    'king' : IDL.Null,
    'nine' : IDL.Null,
    'queen' : IDL.Null,
    'eight' : IDL.Null,
    'seven' : IDL.Null,
  }),
  'suit' : IDL.Variant({
    'diamonds' : IDL.Null,
    'clubs' : IDL.Null,
    'spades' : IDL.Null,
    'hearts' : IDL.Null,
  }),
});
export const Player = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
  'hand' : IDL.Vec(Card),
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalGames' : IDL.Nat,
});
export const GamePhase = IDL.Variant({
  'playing' : IDL.Null,
  'finished' : IDL.Null,
  'waiting' : IDL.Null,
});
export const GameRoom = IDL.Record({
  'status' : RoomStatus,
  'deck' : IDL.Vec(Card),
  'scores' : IDL.Vec(IDL.Nat),
  'currentTurn' : IDL.Nat,
  'players' : IDL.Vec(Player),
  'gameType' : GameType,
  'phase' : GamePhase,
  'roomId' : IDL.Nat,
  'maxPlayers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGameRoom' : IDL.Func([GameType, IDL.Nat], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRoomDetails' : IDL.Func([IDL.Nat], [GameRoom], ['query']),
  'getRoomListByPlayers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, GameRoom))],
      ['query'],
    ),
  'getRoomListByStatus' : IDL.Func(
      [RoomStatus],
      [IDL.Vec(IDL.Tuple(IDL.Nat, GameRoom))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGameRoom' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'leaveGameRoom' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameType = IDL.Variant({
    'santase' : IDL.Null,
    'belot' : IDL.Null,
    'spades' : IDL.Null,
    'durak' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalGames' : IDL.Nat,
  });
  const RoomStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Card = IDL.Record({
    'rank' : IDL.Variant({
      'ace' : IDL.Null,
      'six' : IDL.Null,
      'ten' : IDL.Null,
      'two' : IDL.Null,
      'three' : IDL.Null,
      'five' : IDL.Null,
      'four' : IDL.Null,
      'jack' : IDL.Null,
      'king' : IDL.Null,
      'nine' : IDL.Null,
      'queen' : IDL.Null,
      'eight' : IDL.Null,
      'seven' : IDL.Null,
    }),
    'suit' : IDL.Variant({
      'diamonds' : IDL.Null,
      'clubs' : IDL.Null,
      'spades' : IDL.Null,
      'hearts' : IDL.Null,
    }),
  });
  const Player = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
    'hand' : IDL.Vec(Card),
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalGames' : IDL.Nat,
  });
  const GamePhase = IDL.Variant({
    'playing' : IDL.Null,
    'finished' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const GameRoom = IDL.Record({
    'status' : RoomStatus,
    'deck' : IDL.Vec(Card),
    'scores' : IDL.Vec(IDL.Nat),
    'currentTurn' : IDL.Nat,
    'players' : IDL.Vec(Player),
    'gameType' : GameType,
    'phase' : GamePhase,
    'roomId' : IDL.Nat,
    'maxPlayers' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGameRoom' : IDL.Func([GameType, IDL.Nat], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRoomDetails' : IDL.Func([IDL.Nat], [GameRoom], ['query']),
    'getRoomListByPlayers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, GameRoom))],
        ['query'],
      ),
    'getRoomListByStatus' : IDL.Func(
        [RoomStatus],
        [IDL.Vec(IDL.Tuple(IDL.Nat, GameRoom))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGameRoom' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'leaveGameRoom' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };