/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: Principal;
    username: string;
    hand: Array<Card>;
    wins: bigint;
    losses: bigint;
    totalGames: bigint;
}
export interface Card {
    rank: Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven;
    suit: Variant_diamonds_clubs_spades_hearts;
}
export interface UserProfile {
    username: string;
    wins: bigint;
    losses: bigint;
    totalGames: bigint;
}
export interface GameRoom {
    status: RoomStatus;
    deck: Array<Card>;
    scores: Array<bigint>;
    currentTurn: bigint;
    players: Array<Player>;
    gameType: GameType;
    phase: GamePhase;
    roomId: bigint;
    maxPlayers: bigint;
}
export enum GamePhase {
    playing = "playing",
    finished = "finished",
    waiting = "waiting"
}
export enum GameType {
    santase = "santase",
    belot = "belot",
    spades = "spades",
    durak = "durak"
}
export enum RoomStatus {
    closed = "closed",
    open = "open",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven {
    ace = "ace",
    six = "six",
    ten = "ten",
    two = "two",
    three = "three",
    five = "five",
    four = "four",
    jack = "jack",
    king = "king",
    nine = "nine",
    queen = "queen",
    eight = "eight",
    seven = "seven"
}
export enum Variant_diamonds_clubs_spades_hearts {
    diamonds = "diamonds",
    clubs = "clubs",
    spades = "spades",
    hearts = "hearts"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGameRoom(gameType: GameType, maxPlayers: bigint): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getRoomDetails(roomId: bigint): Promise<GameRoom>;
    getRoomListByPlayers(): Promise<Array<[bigint, GameRoom]>>;
    getRoomListByStatus(status: RoomStatus): Promise<Array<[bigint, GameRoom]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinGameRoom(roomId: bigint, username: string): Promise<void>;
    leaveGameRoom(roomId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Card as _Card, GamePhase as _GamePhase, GameRoom as _GameRoom, GameType as _GameType, Player as _Player, RoomStatus as _RoomStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGameRoom(arg0: GameType, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGameRoom(to_candid_GameType_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGameRoom(to_candid_GameType_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomDetails(arg0: bigint): Promise<GameRoom> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomDetails(arg0);
                return from_candid_GameRoom_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomDetails(arg0);
            return from_candid_GameRoom_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomListByPlayers(): Promise<Array<[bigint, GameRoom]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomListByPlayers();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomListByPlayers();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomListByStatus(arg0: RoomStatus): Promise<Array<[bigint, GameRoom]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomListByStatus(to_candid_RoomStatus_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomListByStatus(to_candid_RoomStatus_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinGameRoom(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGameRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGameRoom(arg0, arg1);
            return result;
        }
    }
    async leaveGameRoom(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGameRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGameRoom(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_Card_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Card {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_GamePhase_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GamePhase): GamePhase {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_GameRoom_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameRoom): GameRoom {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_GameType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameType): GameType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RoomStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomStatus): RoomStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rank: {
        ace: null;
    } | {
        six: null;
    } | {
        ten: null;
    } | {
        two: null;
    } | {
        three: null;
    } | {
        five: null;
    } | {
        four: null;
    } | {
        jack: null;
    } | {
        king: null;
    } | {
        nine: null;
    } | {
        queen: null;
    } | {
        eight: null;
    } | {
        seven: null;
    };
    suit: {
        diamonds: null;
    } | {
        clubs: null;
    } | {
        spades: null;
    } | {
        hearts: null;
    };
}): {
    rank: Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven;
    suit: Variant_diamonds_clubs_spades_hearts;
} {
    return {
        rank: from_candid_variant_n15(_uploadFile, _downloadFile, value.rank),
        suit: from_candid_variant_n16(_uploadFile, _downloadFile, value.suit)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    username: string;
    hand: Array<_Card>;
    wins: bigint;
    losses: bigint;
    totalGames: bigint;
}): {
    id: Principal;
    username: string;
    hand: Array<Card>;
    wins: bigint;
    losses: bigint;
    totalGames: bigint;
} {
    return {
        id: value.id,
        username: value.username,
        hand: from_candid_vec_n12(_uploadFile, _downloadFile, value.hand),
        wins: value.wins,
        losses: value.losses,
        totalGames: value.totalGames
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RoomStatus;
    deck: Array<_Card>;
    scores: Array<bigint>;
    currentTurn: bigint;
    players: Array<_Player>;
    gameType: _GameType;
    phase: _GamePhase;
    roomId: bigint;
    maxPlayers: bigint;
}): {
    status: RoomStatus;
    deck: Array<Card>;
    scores: Array<bigint>;
    currentTurn: bigint;
    players: Array<Player>;
    gameType: GameType;
    phase: GamePhase;
    roomId: bigint;
    maxPlayers: bigint;
} {
    return {
        status: from_candid_RoomStatus_n10(_uploadFile, _downloadFile, value.status),
        deck: from_candid_vec_n12(_uploadFile, _downloadFile, value.deck),
        scores: value.scores,
        currentTurn: value.currentTurn,
        players: from_candid_vec_n17(_uploadFile, _downloadFile, value.players),
        gameType: from_candid_GameType_n20(_uploadFile, _downloadFile, value.gameType),
        phase: from_candid_GamePhase_n22(_uploadFile, _downloadFile, value.phase),
        roomId: value.roomId,
        maxPlayers: value.maxPlayers
    };
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _GameRoom]): [bigint, GameRoom] {
    return [
        value[0],
        from_candid_GameRoom_n8(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    inProgress: null;
}): RoomStatus {
    return "closed" in value ? RoomStatus.closed : "open" in value ? RoomStatus.open : "inProgress" in value ? RoomStatus.inProgress : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ace: null;
} | {
    six: null;
} | {
    ten: null;
} | {
    two: null;
} | {
    three: null;
} | {
    five: null;
} | {
    four: null;
} | {
    jack: null;
} | {
    king: null;
} | {
    nine: null;
} | {
    queen: null;
} | {
    eight: null;
} | {
    seven: null;
}): Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven {
    return "ace" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.ace : "six" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.six : "ten" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.ten : "two" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.two : "three" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.three : "five" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.five : "four" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.four : "jack" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.jack : "king" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.king : "nine" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.nine : "queen" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.queen : "eight" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.eight : "seven" in value ? Variant_ace_six_ten_two_three_five_four_jack_king_nine_queen_eight_seven.seven : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    diamonds: null;
} | {
    clubs: null;
} | {
    spades: null;
} | {
    hearts: null;
}): Variant_diamonds_clubs_spades_hearts {
    return "diamonds" in value ? Variant_diamonds_clubs_spades_hearts.diamonds : "clubs" in value ? Variant_diamonds_clubs_spades_hearts.clubs : "spades" in value ? Variant_diamonds_clubs_spades_hearts.spades : "hearts" in value ? Variant_diamonds_clubs_spades_hearts.hearts : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    santase: null;
} | {
    belot: null;
} | {
    spades: null;
} | {
    durak: null;
}): GameType {
    return "santase" in value ? GameType.santase : "belot" in value ? GameType.belot : "spades" in value ? GameType.spades : "durak" in value ? GameType.durak : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playing: null;
} | {
    finished: null;
} | {
    waiting: null;
}): GamePhase {
    return "playing" in value ? GamePhase.playing : "finished" in value ? GamePhase.finished : "waiting" in value ? GamePhase.waiting : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Array<Card> {
    return value.map((x)=>from_candid_Card_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _GameRoom]>): Array<[bigint, GameRoom]> {
    return value.map((x)=>from_candid_tuple_n25(_uploadFile, _downloadFile, x));
}
function to_candid_GameType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): _GameType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RoomStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomStatus): _RoomStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomStatus): {
    closed: null;
} | {
    open: null;
} | {
    inProgress: null;
} {
    return value == RoomStatus.closed ? {
        closed: null
    } : value == RoomStatus.open ? {
        open: null
    } : value == RoomStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): {
    santase: null;
} | {
    belot: null;
} | {
    spades: null;
} | {
    durak: null;
} {
    return value == GameType.santase ? {
        santase: null
    } : value == GameType.belot ? {
        belot: null
    } : value == GameType.spades ? {
        spades: null
    } : value == GameType.durak ? {
        durak: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
